version: '3.9'

services:
  db:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5431:5432"
    environment:
      - POSTGRES_USER=pizzauser
      - POSTGRES_PASSWORD=pizzapassword
      - POSTGRES_DB=pizzadb

  web:
    build: .
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/pizza_ordering_service
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  postgres_data:
